### ISSUE TITLE
Column index not starting from 0

### ISSUE THREAD

**Issue by freecamel** [GabrieleMaurina/node-red-contrib-machine-learning#4]
Hey, I have noticed that if the input data header is not starting from 0, for example
config['input'] = [1,2,3], it will not add labels at the end as you would have excepted.
Two lines of fixes. Does it make sense?

	if config['shuffle']:
		df = df.sample(frac=1, random_state=config['seed'])

	x_train = df.iloc[: int(r * config['trainingPartition']), config['input']]
	x_test = df.iloc[int(r * config['trainingPartition']) :, config['input']]

## 	# rename column index to start from 0 
	x_train.columns = range(x_train.shape[1])
	x_test.columns = range(x_test.shape[1])

**Comment by freecamel** [comment]
and by the way, is there any way I can contribute and send you pull request?

**Comment by GabrieleMaurina** [comment]
Thanks for the suggestion. I will fix this asap. In the future feel free to send pull requests.

**Comment by freecamel** [comment]
@GabrieleMaurina I do not think I have permission to push code, let alone send pull request. Maybe you have to grant me permissions?
